### ISSUE TITLE
Fail casting numbers, eg Integer to long

### ISSUE THREAD

**Issue by jasonosgood** [jasonosgood/jsonacious#2]
Repro steps in class issues.Issue2. Relevant stacktrace:

```
Exception in thread "main" jsonacious.ParseException: Assignment Issue2.data = 2 failed (line: 1 pos: 14)
    at jsonacious.JSONReader.map(JSONReader.java:140)
    at jsonacious.JSONReader.parse(JSONReader.java:90)
    at jsonacious.JSONReader.parse(JSONReader.java:68)
    at issues.Issue2.main(Issue2.java:24)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
    at issues.Issue2Reflector.put(Issue2Reflector.java:12)
    at jsonacious.JSONReader.map(JSONReader.java:134)
    ... 8 more
```

**Comment by jasonosgood** [comment]
#3 Fixed down/up casting of number values.
